# Generated by Django 2.1.5 on 2019-02-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('code', models.CharField(editable=False, max_length=7, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
            ],
        ),
    ]
